name: Temporary Format Fix

on:
  workflow_dispatch:

jobs:
  format-with-gersemi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run gersemi --fix ğŸ›ï¸
        id: gersemi
        uses: ./.github/actions/run-gersemi
        with:
          failCondition: never # Don't fail the workflow if there are changes
          runMode: format
